### PR TITLE
fixed apiversion clusterrolebinding.yaml and clusterrole.yaml

### PR DESCRIPTION
**Pull request by tux2cool**
this fixes issue 129 submitted by me.

### CODE REVIEW

**Review by ruchir1988 — APPROVED** [review]
LGTM

**Comment by tux2cool** [comment]
> LGTM

What does this mean? What needs to be done to get this merged in?

**Review by ruchir1988 — APPROVED** [review]

**Comment by tux2cool** [comment]
so what are we waiting on now? this is a blocker trying to get it fixed ASAP.

**Comment by nitinmohan87** [comment]
@gargath @JoelSpeed  Any chances of merging this? We would love to keep using this chart and we are currently blocked on this issue.

**Review by pawelwawrzyniak — APPROVED** [review]
Have tested it and works with change on EKS 1.22 (where rbac.authorization.k8s.io must be v1)

**Comment by tux2cool** [comment]
> Have tested it and works with change on EKS 1.22 (where rbac.authorization.k8s.io must be v1)

So when will it be merged?

**Comment by gabeio** [comment]
Unfortunately this repo seems to be unmaintained, there seems to be a similar project for anyone who also has found themselves without wave: https://github.com/stakater/Reloader

**Comment by toelke** [comment]
Thank you for the contribution. I will merge #112 instead of this, as it is the earlier contribution.

**Pull request closed without merging**
